# Generated by Django 5.2.3 on 2025-06-12 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('TC', 'Técnico'), ('GR', 'Graduação'), ('PG', 'Pós-Graduação'), ('EX', 'Extensão')], max_length=2)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alunos', to='gestor.curso')),
            ],
        ),
    ]
